Drop vbox and use qemu everywhere with EFI
rancher/elemental-toolkit pull request #1624
Opened 2022-10-11 10:31 UTC by Itxaka

Signed-off-by: itxaka <igarcia@suse.com>

2022-10-11 13:00 UTC, kkaempf requested changes

2022-10-11 13:02 UTC, Itxaka commented on .github/workflows/build-main-teal-x86_64.yaml
>        - name: Download vagrant box
It is, we just dont generate the vbox one, and instead move to use qemu everywhere with efi

2022-10-11 13:03 UTC, kkaempf commented on .github/workflows/build-main-teal-x86_64.yaml
>        - name: Download vagrant box
So what's the correct `name:` then ?

2022-10-11 13:05 UTC, Itxaka commented on .github/workflows/build-main-teal-x86_64.yaml
>        - name: Download vagrant box
`Download vagrant box` :P

Both are vagrant boxes, they are independent of the driver used. You can see that the artifact name has changed just below on line 455 ;)

2022-10-11 13:11 UTC, kkaempf approved these changes
We should have documentation about the test infrastructure ...

2022-10-11 13:12 UTC, Itxaka commented
> We should have documentation about the test infrastructure ...

We have some under the development.md !

2022-10-17 09:03 UTC, Itxaka commented
for squashfs images a mod is missing somehow:

`error: ../../grub-core/fs/fshelp.c:258:file /grub2/arm64-efi/xzio.mod not found`

2022-10-18 13:27 UTC, merged