Add init command
rancher/elemental-toolkit pull request #1767
Opened 2023-05-23 13:23 UTC by frelon

The init command is meant to be run in a container build step and extracts config-files needed for an elemental derivative.

This PR includes a way to turn on/off different features of the elemental-toolkit. The standard features included here are:
* immutable-rootfs
* grub-config
* elemental-setup
* dracut-config
* cloud-config-defaults
* cloud-config-essentials

An example dockerfile:

```
FROM rancher/elemental-cli:latest AS elemental-cli
FROM opensuse/tumbleweed as default

RUN zypper install -y grub2 grub2-x86_64-efi grub2-x86_64-efi-extras shim dracut kernel kernel-firmware-all systemd \
                      bash syslinux lvm2 parted dosfstools e2fsprogs rsync util-linux-systemd coreutils \
                      squashfs NetworkManager device-mapper iproute2 tar curl ca-certificates ca-certificates-mozilla \
                      procps openssl openssh vim-small less iputils bind-utils wget jq

COPY --from=elemental-cli /usr/bin/elemental /usr/bin/elemental

RUN systemctl enable NetworkManager
RUN elemental init --force immutable-rootfs,grub-config,dracut-config
```

Fixes rancher/elemental-toolkit#1766

2023-06-09 09:11 UTC, fgiudici approved these changes
Great PR! 
created a derivative from tumbleweed with the elemental init cmd 🎉

2023-06-14 12:52 UTC, davidcassany requested changes
Looks good, I just have few doubts about some details.

Should be easy to arrange, probably it is already fine and I just missed something.

I think we also should adapt the specfile of the elemental-toolkit RPM so we can merge it being transparent to elemental teal. This way we could merge without necessarily breaking `Dev` and apply the transition in Elemental Teal in smaller PRs.

2023-06-15 10:26 UTC, frelon commented on pkg/action/init.go
> +	firstboot := map[string]string{"next_entry": "recovery"}
Yep, this was copied from the old `grub2-config` luet package, maybe we should just drop it?

2023-06-16 08:15 UTC, frelon commented on pkg/action/init.go
> +	firstboot := map[string]string{"next_entry": "recovery"}
I removed it :+1:

2023-06-16 08:28 UTC, frelon commented on pkg/features/features.go
> +	FeatureCloudConfig     = "cloud-config"
Good idea! I split cloud-config into cloud-config-defaults and cloud-config-essentials, where the essentials are the services used in teal.

2023-06-16 08:32 UTC, frelon commented
@davidcassany I did the changes to obs to keep Dev in a working condition and split the `cloud-config` feature into two, let me know what you think! :+1:

2023-06-16 15:33 UTC, merged