feat(): call partprobe after udevadm
rancher/elemental-toolkit pull request #1841
Opened 2023-10-06 13:42 UTC by shanduur

I encountered an issue while running the elemental toolkit in the Earthly, where the partition device 1 of device `/dev/loop2` could not be found. Calling `partprobe` shows the partition that we want. The fix is small and simple, and does not introduce additional dependency, as `partprobe` is part of `parted` package.

```log
buildkitsandbox:/work # qemu-img create -f raw a.img 32G
Formatting 'a.img', fmt=raw size=34359738368
buildkitsandbox:/work # losetup -f --show a.img 
/dev/loop2
buildkitsandbox:/work # elemental install --debug --firmware efi --system.uri 'oci:ghcr.io/doomshrine/cadia:v1.0.0' /dev/loop2
DEBU[2023-10-06T13:33:27Z] Starting elemental version v1.0.0 on commit 17e4895c6a6863f7eb22b0c4fdddd2dc297f71b8 
INFO[2023-10-06T13:33:27Z] Reading configuration from '/etc/elemental'  
DEBU[2023-10-06T13:33:27Z] Full config loaded: &v1.RunConfig{
  Reboot: false,
  PowerOff: false,
  EjectCD: false,
  Config: v1.Config{
    Logger: &v1.logrusWrapper{ // p0
      Logger: &logrus.Logger{
        Out: &os.File{},
        Hooks: logrus.LevelHooks{},
        Formatter: &logrus.TextFormatter{
          ForceColors: true,
          DisableColors: false,
          ForceQuote: false,
          DisableQuote: false,
          EnvironmentOverrideColors: false,
          DisableTimestamp: false,
          FullTimestamp: true,
          TimestampFormat: "",
          DisableSorting: false,
          SortingFunc: ,
          DisableLevelTruncation: false,
          PadLevelText: false,
          QuoteEmptyFields: false,
          FieldMap: logrus.FieldMap(nil),
          CallerPrettyfier: ,
        },
        ReportCaller: false,
        Level: 5,
        ExitFunc: os.Exit,
        BufferPool: nil,
      },
    },
    Fs: &vfs.osfs{}, // p1
    Mounter: &mount.Mounter{},
    Runner: &v1.RealRunner{ // p2
      Logger: p0,
    },
    Syscall: &v1.RealSyscall{},
    CloudInitRunner: &cloudinit.YipCloudInitRunner{},
    ImageExtractor: v1.OCIImageExtractor{},
    Client: &http.Client{},
    Platform: &v1.Platform{
      OS: "linux",
      Arch: "arm64",
      GolangArch: "arm64",
    },
    Cosign: false,
    Verify: false,
    CosignPubKey: "",
    LocalImage: false,
    Arch: "",
    SquashFsCompressionConfig: []string{
      "-comp",
      "xz",
      "-Xbcj",
      "arm",
    },
    SquashFsNoCompression: false,
    CloudInitPaths: []string{
      "/system/oem",
      "/oem/",
      "/usr/local/cloud-config/",
    },
    Strict: false,
  },
} 
DEBU[2023-10-06T13:33:27Z] Loaded install spec: &v1.InstallSpec{
  Target: "",
  Firmware: "efi",
  PartTable: "gpt",
  Partitions: v1.ElementalPartitions{
    BIOS: nil,
    EFI: &v1.Partition{
      Name: "efi",
      FilesystemLabel: "COS_GRUB",
      Size: 64,
      FS: "vfat",
      Flags: []string{
        "esp",
      },
      MountPoint: "/run/cos/efi",
      Path: "",
      Disk: "",
    },
    OEM: &v1.Partition{
      Name: "oem",
      FilesystemLabel: "COS_OEM",
      Size: 64,
      FS: "ext4",
      Flags: []string{}, // p0
      MountPoint: "/run/cos/oem",
      Path: "",
      Disk: "",
    },
    Recovery: &v1.Partition{
      Name: "recovery",
      FilesystemLabel: "COS_RECOVERY",
      Size: 4096,
      FS: "ext4",
      Flags: p0,
      MountPoint: "/run/cos/recovery",
      Path: "",
      Disk: "",
    },
    State: &v1.Partition{
      Name: "state",
      FilesystemLabel: "COS_STATE",
      Size: 8192,
      FS: "ext4",
      Flags: p0,
      MountPoint: "/run/cos/state",
      Path: "",
      Disk: "",
    },
    Persistent: &v1.Partition{
      Name: "persistent",
      FilesystemLabel: "COS_PERSISTENT",
      Size: 0,
      FS: "ext4",
      Flags: p0,
      MountPoint: "/run/cos/persistent",
      Path: "",
      Disk: "",
    },
  },
  ExtraPartitions: nil,
  NoFormat: false,
  Force: false,
  CloudInit: nil,
  Iso: "",
  GrubDefEntry: "",
  Active: v1.Image{
    File: "/run/cos/state/cOS/active.img",
    Label: "COS_ACTIVE",
    Size: 0,
    FS: "ext2",
    Source: &v1.ImageSource{},
    MountPoint: "/run/cos/active",
    LoopDevice: "",
  },
  Recovery: v1.Image{
    File: "/run/cos/recovery/cOS/recovery.img",
    Label: "COS_SYSTEM",
    Size: 0,
    FS: "ext2",
    Source: &v1.ImageSource{},
    MountPoint: "",
    LoopDevice: "",
  },
  Passive: v1.Image{
    File: "/run/cos/state/cOS/passive.img",
    Label: "COS_PASSIVE",
    Size: 0,
    FS: "ext2",
    Source: &v1.ImageSource{},
    MountPoint: "",
    LoopDevice: "",
  },
  GrubConf: "/etc/cos/grub.cfg",
  DisableBootEntry: false,
} 
INFO[2023-10-06T13:33:27Z] Install called                               
DEBU[2023-10-06T13:33:27Z] Running cmd: 'blkdeactivate --lvmoptions retry,wholevg --dmoptions force,retry --errors' 
DEBU[2023-10-06T13:33:27Z] blkdeactivate command output: Deactivating block devices: 
INFO[2023-10-06T13:33:27Z] Partitioning device...                       
DEBU[2023-10-06T13:33:27Z] Running cmd: 'parted --script --machine -- /dev/loop2 unit s mklabel gpt' 
DEBU[2023-10-06T13:33:27Z] Running cmd: 'parted --script --machine -- /dev/loop2 unit s print' 
DEBU[2023-10-06T13:33:27Z] Adding partition efi                         
DEBU[2023-10-06T13:33:27Z] Running cmd: 'parted --script --machine -- /dev/loop2 unit s mkpart efi fat32 2048 133119 set 1 esp on' 
DEBU[2023-10-06T13:33:27Z] partitioner output:                          
DEBU[2023-10-06T13:33:27Z] Running cmd: 'parted --script --machine -- /dev/loop2 unit s print' 
DEBU[2023-10-06T13:33:27Z] Trying to find the partition device 1 of device /dev/loop2 (try number 1) 
DEBU[2023-10-06T13:33:27Z] Running cmd: 'udevadm settle'                
DEBU[2023-10-06T13:33:28Z] Trying to find the partition device 1 of device /dev/loop2 (try number 2) 
DEBU[2023-10-06T13:33:28Z] Running cmd: 'udevadm settle'                
DEBU[2023-10-06T13:33:29Z] Trying to find the partition device 1 of device /dev/loop2 (try number 3) 
DEBU[2023-10-06T13:33:29Z] Running cmd: 'udevadm settle'                
DEBU[2023-10-06T13:33:31Z] Trying to find the partition device 1 of device /dev/loop2 (try number 4) 
DEBU[2023-10-06T13:33:31Z] Running cmd: 'udevadm settle'                
DEBU[2023-10-06T13:33:32Z] Trying to find the partition device 1 of device /dev/loop2 (try number 5) 
DEBU[2023-10-06T13:33:32Z] Running cmd: 'udevadm settle'                
DEBU[2023-10-06T13:33:33Z] Trying to find the partition device 1 of device /dev/loop2 (try number 6) 
DEBU[2023-10-06T13:33:33Z] Running cmd: 'udevadm settle'                
DEBU[2023-10-06T13:33:34Z] Trying to find the partition device 1 of device /dev/loop2 (try number 7) 
DEBU[2023-10-06T13:33:34Z] Running cmd: 'udevadm settle'                
DEBU[2023-10-06T13:33:35Z] Trying to find the partition device 1 of device /dev/loop2 (try number 8) 
DEBU[2023-10-06T13:33:35Z] Running cmd: 'udevadm settle'                
DEBU[2023-10-06T13:33:36Z] Trying to find the partition device 1 of device /dev/loop2 (try number 9) 
DEBU[2023-10-06T13:33:36Z] Running cmd: 'udevadm settle'                
DEBU[2023-10-06T13:33:37Z] Trying to find the partition device 1 of device /dev/loop2 (try number 10) 
DEBU[2023-10-06T13:33:37Z] Running cmd: 'udevadm settle'                
DEBU[2023-10-06T13:33:38Z] Trying to find the partition device 1 of device /dev/loop2 (try number 11) 
DEBU[2023-10-06T13:33:38Z] Running cmd: 'udevadm settle'                
Error: 1 error occurred:
        * could not find partition device '/dev/loop2p1' for partition 1

buildkitsandbox:/work # partprobe
buildkitsandbox:/work # lsblk
NAME      MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
loop0       7:0    0  633M  1 loop 
loop1       7:1    0   32G  0 loop 
`-loop1p1 259:2    0   64M  0 part 
loop2       7:2    0   32G  0 loop 
`-loop2p1 259:3    0   64M  0 part 
nbd0       43:0    0    0B  0 disk 
nbd1       43:32   0    0B  0 disk 
nbd2       43:64   0    0B  0 disk 
nbd3       43:96   0    0B  0 disk 
nbd4       43:128  0    0B  0 disk 
nbd5       43:160  0    0B  0 disk 
nbd6   [...]

2023-10-06 16:30 UTC, kkaempf approved these changes
lgtm

2023-10-09 07:46 UTC, frelon reviewed
Nice catch! If you also update the tests in `pkg/partitioner/partitioner_test.go` I will be happy to merge this!

2023-10-09 08:08 UTC, davidcassany requested changes
Thanks much for contribution and detail error report, this is highly appreciated.

I am curious to understand how this could happen... parted already signals the kernel, hence partprobe should not needed at all when partitioning with parted, at most waiting for udev to find it.

I am not against the change, I am wondering if this is hiding something else.

Moreover I am pretty much convinced we should be moving from `parted` to `sgdisk`, then in that case, using the partprobe will be required.

This also makes me wonder if `partprobe` call should here or not. What if we include the call as part of `PartCall.WriteChanges` method? This is where I'd include it and expect to need it only once. There is where be placed in an eventual `sgdisk` wrapper implementing the same current parted wrapper API.

Would you mind giving it a try? Basically adding something like
```golang
// Notify kernel of partition table changes, swallows errors, just a best effort call
_, _ = pc.runner.Run("partprobe", pc.dev)

```

in https://github.com/rancher/elemental-toolkit/blob/2717827f8c1f446feeee300038e7b8162c853388/pkg/partitioner/parted.go#L121-L131 before returning.

I'd go for such an approach if this also solves your issue.

2023-10-09 15:24 UTC, shanduur commented on pkg/partitioner/disk.go
> +		_, _ = dev.runner.Run("partprobe")
Will fix that!

2023-10-09 18:02 UTC, shanduur commented
Looks like this did not help, at least not in full extent. `lsblk` finds the partition after calling `partprobe`, but there is no `/dev/loop1p1`...

Command run is `earthly --allow-privileged +raw-image` for the following Earthfile:

```Earthly
# ./Earthfile
# cmd: earthly --allow-privileged +raw-image
VERSION 0.7
FROM scratch

ARG --global VERSION='v0.0.0'
ARG --global REPO='ghcr.io/doomshrine/cadia'

toolkit:
    FROM docker.io/library/golang:1.21
    GIT CLONE --branch fix-partprobe https://github.com/shanduur/elemental-toolkit.git /elemental-toolkit
    WORKDIR /elemental-toolkit
    ENV CGO_ENABLED=0
    RUN make build-cli
    SAVE ARTIFACT /elemental-toolkit/build/elemental

depenedencies:
    FROM docker.io/opensuse/leap:15.5

    # install kernel, systemd, dracut, grub2 and other required tools
    RUN ARCH=$(uname -m); \
        if [[ $ARCH == "aarch64" ]]; then ARCH="arm64"; fi; \
        zypper --non-interactive install --no-recommends -- \
            curl \
            containerd \
            device-mapper \
            dosfstools \
            dracut \
            e2fsprogs \
            findutils \
            gptfdisk \
            grub2 \
            grub2-${ARCH}-efi \
            gzip \
            haveged \
            kernel-default \
            less \
            lvm2 \
            mtools \
            neovim \
            NetworkManager \
            open-iscsi \
            openssh-clients \
            openssh-server \
            parted \
            rsync \
            sed \
            shim \
            squashfs \
            sudo \
            systemd \
            tar \
            timezone \
            which \
            xorriso

    COPY +toolkit/elemental /usr/bin/elemental

container-image:
    FROM +depenedencies

    # Update os-release file with some metadata
    RUN echo IMAGE_REPO=\"${REPO}\"             >> /etc/os-release && \
        echo IMAGE_TAG=\"${VERSION}\"           >> /etc/os-release && \
        echo IMAGE=\"${REPO}:${VERSION}\"       >> /etc/os-release && \
        echo TIMESTAMP="`date +'%Y%m%d%H%M%S'`" >> /etc/os-release && \
        echo GRUB_ENTRY_NAME=\"Elemental\"      >> /etc/os-release


    # Enable essential services
    RUN systemctl enable NetworkManager.service

    # Enable /tmp to be on tmpfs
    RUN cp /usr/share/systemd/tmp.mount /etc/systemd/system

    # Generate initrd with required elemental services
    RUN elemental init -f && \
        kernel=$(ls /boot/Image-* | head -n1) && \
        if [ -e "$kernel" ]; then ln -sf "${kernel#/boot/}" /boot/vmlinuz; fi && \
        rm -rf /var/log/update* && \
        >/var/log/lastlog && \
        rm -rf /boot/vmlinux*

    # Good for validation after the build
    ENTRYPOINT [ "/usr/bin/bash" ]

    SAVE IMAGE "${REPO}:${VERSION}"

raw-image:
    FROM +depenedencies

    RUN zypper --non-interactive install --no-recommends -- \
        qemu-tools

    WORKDIR /work

    RUN qemu-img create -f raw "disk-$(uname -m).img" 32G

    RUN --privileged \
        set -e; \
        set -o pipefail; \
        export DEVICE="$(losetup -f --show disk-$(uname -m).img)"; \
        echo "device is ${DEVICE}"; \
        if ! elemental install  --debug --firmware efi --system.uri "oci:${REPO}:${VERSION}" "${DEVICE}"; then \
            echo "error caught, removing loop device ${DEVICE}"; \
            echo "--------- LSBLK ---------"; \
            lsblk; \
            echo "--------- LS /dev/ ---------"; \
            ls /dev/; \
            losetup -d "${DEVICE}"; \
            exit 1; \
        fi; \
        echo "finished, removing loop device ${DEVICE}"; \
        lsblk; \
        ls /dev/; \
        losetup -d "${DEVICE}";
```

Full execution log is attached here:
[log.txt](https://github.com/rancher/elemental-toolkit/files/12849068/log.txt)

This PR turns into issue to be honest... Should I open one?

2023-10-09 18:13 UTC, shanduur commented
Ah, I see... In the container, this is the same issue as the https://github.com/moby/moby/issues/27886#issuecomment-257185319 . The solution is to call `mknod` if the comments don't lie. At this point I am unsure if this is something that you want to be included in the elemental toolkit.

2023-10-09 20:38 UTC, davidcassany commented
Ah I see, so you were building inside a container... yes, this makes it pretty different as it is likely there is no udev in the system and so on 🤔 

Then I'd suggest trying to get a different perspective, what are you trying to achieve? Are you trying to build a disk image? I am asking because what you are executing here is the installer and I'd say it is a fair assumption not being in a container in that context.

I am also asking because a disk builder command is something in our radar and something we would like to invest some time on. In addition we would be considering containerized builds under certain constraints to allow non privileged builds. Would a command like `elemental build-disk` (produces raw image with a single recovery partition that gets expanded to the disk geometry at first boot) would be something that suits your needs?

2023-10-09 21:47 UTC, shanduur commented
Yes, exactly! I am trying to build an ISO/RAW image in the container, something that will be a part of a Tekton pipeline? Wanted to use Earthly for that, but after some tinkering I feel like the approach with plain image will be much easier to achieve, and I am not getting so many cryptic errors. I removed `mknod`, as even it worked in the Earthly, it failed in the plain Docker container - the call to `partprobe` was enough in case of privileged container. 

If you still think this is a valuable addition, I can fix the tests.

2023-10-10 06:59 UTC, kkaempf commented
I experienced similar problems when porting the [Raspberry image generator](https://build.opensuse.org/package/show/isv:Rancher:Elemental:Stable/elemental-post-build-generate-rpi-image) from [SLE Micro 5.4](https://build.opensuse.org/package/show/isv:Rancher:Elemental:Stable/elemental-post-build-generate-rpi-image) to [SLE Micro 5.5](https://build.opensuse.org/package/show/isv:Rancher:Elemental:Dev/elemental-post-build-generate-rpi-image)

In 5.4 the following works and creates the right device entries
* create empty image file
* run `losetup` on the (unpartitioned) image file
* run parted on the loop device

In 5.5 the approach above didn't work, I had to change it to
* create empty image file
* run parted on the image file
* run `lopsetup --partscan` on the (partitioned) image file

2023-10-11 08:26 UTC, davidcassany commented
@shanduur I have updated and refined an old PR we had around the disks creation here #1794, I am wondering if such an approach would help for your particular use cases. If not I am also interested on knowing what would be missing from your perspective.

In any case I think this PR can be closed if this is fine with you, so far I don't see a proper solution to allow building disks inside containers by calling elemental install over loop devices. I'd say we should not support that approach, even if we find a solution for your current specific use case I don't think we can guarantee this will always work, dealing with block devices inside containers where there might be or not udev and other essential services opens a wide range of potential issues.

2023-10-11 08:29 UTC, shanduur commented
Ah, this looks exactly what I need. I will test it ASAP and share the feedback.

2023-10-11 08:30 UTC, closed without merging